//! Composite PRIMARY KEY and AUTOINCREMENT DDL rendering.

use toolu_orm_core::column::{ColumnDef, ColumnType};
use toolu_orm_core::dialect::Dialect;
use toolu_orm_core::diff::Operation;
use toolu_orm_core::sql::generate_sql_for;
use toolu_orm_core::table::TableDef;

fn text_col(name: &str) -> ColumnDef {
  ColumnDef {
    name: name.to_owned(),
    column_type: ColumnType::Text,
    primary_key: false,
    not_null: true,
    default: None,
    unique: false,
    references: None,
    on_delete: None,
    on_update: None,
    check: None,
    unindexed: false,
    autoincrement: false,
  }
}

#[test]
fn composite_primary_key_renders_as_table_constraint() {
  let table = TableDef {
    name: "memory_tags".to_owned(),
    columns: vec![text_col("memory_id"), text_col("tag")],
    indexes: vec![],
    primary_key: vec!["memory_id".to_owned(), "tag".to_owned()],
    strict: false,
    kind: toolu_orm_core::table::TableKind::Ordinary,
  };
  let sql = generate_sql_for(&[Operation::CreateTable { table }], Dialect::Sqlite);
  assert!(
    sql.contains(r#"PRIMARY KEY ("memory_id", "tag")"#),
    "expected trailing composite PK, got: {sql}"
  );
  assert!(
    !sql.contains("\"memory_id\" TEXT NOT NULL PRIMARY KEY"),
    "columns must not carry inline PRIMARY KEY when table-level key is set: {sql}"
  );
}

#[test]
fn autoincrement_renders_sqlite_primary_key_autoincrement() {
  let table = TableDef {
    name: "retrieval_log".to_owned(),
    columns: vec![ColumnDef {
      name: "id".to_owned(),
      column_type: ColumnType::Integer,
      primary_key: true,
      not_null: false,
      default: None,
      unique: false,
      references: None,
      on_delete: None,
      on_update: None,
      check: None,
      unindexed: false,
      autoincrement: true,
    }],
    indexes: vec![],
    primary_key: vec![],
    strict: false,
    kind: toolu_orm_core::table::TableKind::Ordinary,
  };
  let sql = generate_sql_for(&[Operation::CreateTable { table }], Dialect::Sqlite);
  assert!(
    sql.contains(r#""id" INTEGER PRIMARY KEY AUTOINCREMENT"#),
    "expected AUTOINCREMENT, got: {sql}"
  );
}

#[test]
fn autoincrement_maps_to_identity_on_postgres() {
  let table = TableDef {
    name: "retrieval_log".to_owned(),
    columns: vec![ColumnDef {
      name: "id".to_owned(),
      column_type: ColumnType::Integer,
      primary_key: true,
      not_null: false,
      default: None,
      unique: false,
      references: None,
      on_delete: None,
      on_update: None,
      check: None,
      unindexed: false,
      autoincrement: true,
    }],
    indexes: vec![],
    primary_key: vec![],
    strict: false,
    kind: toolu_orm_core::table::TableKind::Ordinary,
  };
  let sql = generate_sql_for(&[Operation::CreateTable { table }], Dialect::Postgres);
  assert!(
    sql.contains("GENERATED BY DEFAULT AS IDENTITY"),
    "expected IDENTITY mapping, got: {sql}"
  );
  assert!(
    sql.contains("PRIMARY KEY"),
    "expected PRIMARY KEY, got: {sql}"
  );
}
