//! Schema, typed columns and row types shared by the three live upsert
//! suites (rusqlite, libsql, Postgres).
//!
//! The tables are the ones issue #108 names: `memories` with columns an
//! upsert must preserve, `memory_links` referencing it with
//! `ON DELETE CASCADE` so `INSERT OR REPLACE` can be told apart from
//! `DO UPDATE`, and `code_symbols` with a generated id and a composite
//! unique key. `#[derive(FromRow)]` follows whichever shape orm-core
//! compiled, so one row type serves every lane.

use toolu_orm_core::column::{Integer, Text};
use toolu_orm_core::query_column::Column;
use toolu_orm_macros::FromRow;

pub const MEMORY_ID: Column<Text> = Column::new("memories", "id");
pub const BODY: Column<Text> = Column::new("memories", "body");
pub const WORKSPACE_ID: Column<Text> = Column::new("memories", "workspace_id");
pub const USED_COUNT: Column<Integer> = Column::new("memories", "used_count");
pub const LAST_USED: Column<Text> = Column::new("memories", "last_used");
pub const MEMORY_COLUMNS: [&str; 5] = ["id", "body", "workspace_id", "used_count", "last_used"];

pub const LINK_ID: Column<Text> = Column::new("memory_links", "id");
pub const LINK_MEMORY_ID: Column<Text> = Column::new("memory_links", "memory_id");
pub const LINK_NOTE: Column<Text> = Column::new("memory_links", "note");
pub const LINK_COLUMNS: [&str; 3] = ["id", "memory_id", "note"];

pub const SYMBOL_ID: Column<Integer> = Column::new("code_symbols", "id");
pub const REPO: Column<Text> = Column::new("code_symbols", "repo");
pub const PATH: Column<Text> = Column::new("code_symbols", "path");
pub const INDEXED_AT: Column<Text> = Column::new("code_symbols", "indexed_at");
pub const SYMBOL_COLUMNS: [&str; 4] = ["id", "repo", "path", "indexed_at"];

/// `strftime` format for an ISO-8601 timestamp with milliseconds — the one
/// comemory's `code_row.rs` writes.
pub const ISO_FORMAT: &str = "%Y-%m-%dT%H:%M:%fZ";

pub const SQLITE_DDL: &str = "
  CREATE TABLE memories (
    id TEXT PRIMARY KEY,
    body TEXT NOT NULL,
    workspace_id TEXT,
    used_count INTEGER NOT NULL DEFAULT 0,
    last_used TEXT
  );
  CREATE TABLE memory_links (
    id TEXT PRIMARY KEY,
    memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    note TEXT NOT NULL
  );
  CREATE TABLE code_symbols (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    repo TEXT NOT NULL,
    path TEXT NOT NULL,
    indexed_at TEXT NOT NULL,
    UNIQUE (repo, path)
  );
";

/// The same tables with Postgres types: `BIGINT` for what a bound
/// `Value::Integer` binds as, and an identity column for the generated id.
pub const POSTGRES_DDL: &str = "
  CREATE TABLE memories (
    id TEXT PRIMARY KEY,
    body TEXT NOT NULL,
    workspace_id TEXT,
    used_count BIGINT NOT NULL DEFAULT 0,
    last_used TEXT
  );
  CREATE TABLE memory_links (
    id TEXT PRIMARY KEY,
    memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    note TEXT NOT NULL
  );
  CREATE TABLE code_symbols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo TEXT NOT NULL,
    path TEXT NOT NULL,
    indexed_at TEXT NOT NULL,
    UNIQUE (repo, path)
  );
";

/// Field order matches [`MEMORY_COLUMNS`], which is how the derive decodes.
#[derive(FromRow, Debug, Clone, PartialEq)]
pub struct Memory {
  pub id: String,
  pub body: String,
  pub workspace_id: Option<String>,
  pub used_count: i64,
  pub last_used: Option<String>,
}

/// Field order matches [`LINK_COLUMNS`].
#[derive(FromRow, Debug, Clone, PartialEq)]
pub struct MemoryLink {
  pub id: String,
  pub memory_id: String,
  pub note: String,
}

/// Field order matches [`SYMBOL_COLUMNS`].
#[derive(FromRow, Debug, Clone, PartialEq)]
pub struct CodeSymbol {
  pub id: i64,
  pub repo: String,
  pub path: String,
  pub indexed_at: String,
}

/// One `RETURNING "id"` projection.
#[derive(FromRow, Debug, Clone, PartialEq)]
pub struct GeneratedId {
  pub id: i64,
}
